repository = "https://github.com/nikstern/temper.git"
revision = "f0c431ed0b2a19e3f7834a95cba884ad15085651"
manifest_patterns = ["Cargo.toml", "crates/**/Cargo.toml", "os-apps/**/Cargo.toml"]
lockfile_patterns = ["Cargo.lock", "crates/**/Cargo.lock", "os-apps/**/Cargo.lock"]
