repository = "https://github.com/nikstern/temper.git"
revision = "e8ff002bde3e9512385c2856d733210600e7c253"
manifest_patterns = ["Cargo.toml", "crates/**/Cargo.toml", "os-apps/**/Cargo.toml"]
lockfile_patterns = ["Cargo.lock", "crates/**/Cargo.lock", "os-apps/**/Cargo.lock"]
