[package]
name = "plan-review-feedback-handler"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[workspace]

[dependencies]
serde_json = "1"
session-tree-lib = { path = "../session-tree-lib" }
temper-wasm-sdk = { git = "https://github.com/nikstern/temper.git", rev = "e8ff002b" }
wasm-helpers = { path = "../wasm-helpers" }
