[package]
name = "patrol-request-router"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "patrol_request_router"
path = "src/wasm_entry.rs"
test = false

[workspace]

[dependencies]
temper-wasm-sdk = { git = "https://github.com/nikstern/temper.git", rev = "f0c431ed0b2a19e3f7834a95cba884ad15085651" }
