[package]
name = "patrol-request-router"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "patrol_request_router"
path = "src/wasm_entry.rs"
test = false

[workspace]

[dependencies]
temper-wasm-sdk = { git = "https://github.com/nikstern/temper.git", rev = "e3dfe852e7a7373cef8bddfe2e3b8bcad8f94a0a" }
