[package]
name = "patrol-request-router"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "patrol_request_router"
path = "src/wasm_entry.rs"
test = false

[workspace]

[dependencies]
temper-wasm-sdk = { git = "https://github.com/nikstern/temper.git", rev = "e8ff002bde3e9512385c2856d733210600e7c253" }
