// @generated by temper-codegen; do not edit.
use temper_wasm_sdk::data::*;

fn invalid_generated_value(error: serde_json::Error) -> ModuleDataError { ModuleDataError::new(ModuleDataErrorKind::InvalidRequest, "GeneratedValueEncodingFailed", error.to_string(), Retryability::Never) }

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct SessionId(pub String);

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Session {
    #[serde(rename = "ActivePlanId")]
    pub active_plan_id: Option<String>,
    #[serde(rename = "AgentId")]
    pub agent_id: Option<String>,
    #[serde(rename = "ChildSessionIds")]
    pub child_session_ids: Option<String>,
    #[serde(rename = "CompactionAuthRetryCount")]
    pub compaction_auth_retry_count: Option<i64>,
    #[serde(rename = "CompactionCount")]
    pub compaction_count: Option<i64>,
    #[serde(rename = "CompactionModel")]
    pub compaction_model: Option<String>,
    #[serde(rename = "CompactionSkippedLeafId")]
    pub compaction_skipped_leaf_id: Option<String>,
    #[serde(rename = "CompactionSkippedReason")]
    pub compaction_skipped_reason: Option<String>,
    #[serde(rename = "ContextTokens")]
    pub context_tokens: Option<i64>,
    #[serde(rename = "Conversation")]
    pub conversation: Option<String>,
    #[serde(rename = "ConversationFileId")]
    pub conversation_file_id: Option<String>,
    #[serde(rename = "CostCents")]
    pub cost_cents: Option<String>,
    #[serde(rename = "ErrorMessage")]
    pub error_message: Option<String>,
    #[serde(rename = "FileManifestId")]
    pub file_manifest_id: Option<String>,
    #[serde(rename = "FollowUpCount")]
    pub follow_up_count: Option<i64>,
    #[serde(rename = "GenAiParentSpanId")]
    pub gen_ai_parent_span_id: Option<String>,
    #[serde(rename = "GenAiParentTraceId")]
    pub gen_ai_parent_trace_id: Option<String>,
    #[serde(rename = "HasResult")]
    pub has_result: Option<bool>,
    #[serde(rename = "HeartbeatTimeoutSeconds")]
    pub heartbeat_timeout_seconds: Option<String>,
    #[serde(rename = "HookPolicy")]
    pub hook_policy: Option<String>,
    #[serde(rename = "Id")]
    pub id: String,
    #[serde(rename = "InputTokens")]
    pub input_tokens: Option<i64>,
    #[serde(rename = "KeepRecentTokens")]
    pub keep_recent_tokens: Option<String>,
    #[serde(rename = "LastHeartbeatAt")]
    pub last_heartbeat_at: Option<String>,
    #[serde(rename = "LastProgressAt")]
    pub last_progress_at: Option<String>,
    #[serde(rename = "MaxFollowUps")]
    pub max_follow_ups: Option<String>,
    #[serde(rename = "MaxProvisionChecks")]
    pub max_provision_checks: Option<String>,
    #[serde(rename = "MaxTurns")]
    pub max_turns: Option<String>,
    #[serde(rename = "Model")]
    pub model: Option<String>,
    #[serde(rename = "OutputTokens")]
    pub output_tokens: Option<i64>,
    #[serde(rename = "ParentSessionId")]
    pub parent_session_id: Option<String>,
    #[serde(rename = "PendingDecisionId")]
    pub pending_decision_id: Option<String>,
    #[serde(rename = "PendingToolCalls")]
    pub pending_tool_calls: Option<String>,
    #[serde(rename = "PendingToolContext")]
    pub pending_tool_context: Option<String>,
    #[serde(rename = "PrePlanToolsEnabled")]
    pub pre_plan_tools_enabled: Option<String>,
    #[serde(rename = "PreparedContextBytes")]
    pub prepared_context_bytes: Option<i64>,
    #[serde(rename = "PreparedContextContentFilesLoaded")]
    pub prepared_context_content_files_loaded: Option<i64>,
    #[serde(rename = "PreparedContextEntriesLoaded")]
    pub prepared_context_entries_loaded: Option<i64>,
    #[serde(rename = "PreparedContextFileId")]
    pub prepared_context_file_id: Option<String>,
    #[serde(rename = "PreparedContextInlineJson")]
    pub prepared_context_inline_json: Option<String>,
    #[serde(rename = "ProgressToken")]
    pub progress_token: Option<i64>,
    #[serde(rename = "ProjectHarnessId")]
    pub project_harness_id: Option<String>,
    #[serde(rename = "ProjectId")]
    pub project_id: Option<String>,
    #[serde(rename = "Provider")]
    pub provider: Option<String>,
    #[serde(rename = "ProviderAuthCheckedAtMs")]
    pub provider_auth_checked_at_ms: Option<String>,
    #[serde(rename = "ProviderAuthError")]
    pub provider_auth_error: Option<String>,
    #[serde(rename = "ProviderAuthRetryCount")]
    pub provider_auth_retry_count: Option<i64>,
    #[serde(rename = "ProviderAuthStatus")]
    pub provider_auth_status: Option<String>,
    #[serde(rename = "ProviderOptionsJson")]
    pub provider_options_json: Option<String>,
    #[serde(rename = "ProviderRequestBytes")]
    pub provider_request_bytes: Option<i64>,
    #[serde(rename = "ProviderResponseBytes")]
    pub provider_response_bytes: Option<i64>,
    #[serde(rename = "ProviderResponseFileId")]
    pub provider_response_file_id: Option<String>,
    #[serde(rename = "ProviderResponseInlineJson")]
    pub provider_response_inline_json: Option<String>,
    #[serde(rename = "ProvisionCheckCount")]
    pub provision_check_count: Option<i64>,
    #[serde(rename = "ReplFileId")]
    pub repl_file_id: Option<String>,
    #[serde(rename = "ReplyAttachmentsJson")]
    pub reply_attachments_json: Option<String>,
    #[serde(rename = "ReplyChannelEntityId")]
    pub reply_channel_entity_id: Option<String>,
    #[serde(rename = "ReplyChannelId")]
    pub reply_channel_id: Option<String>,
    #[serde(rename = "ReplyChannelType")]
    pub reply_channel_type: Option<String>,
    #[serde(rename = "ReplyRouteSource")]
    pub reply_route_source: Option<String>,
    #[serde(rename = "ReplyThreadId")]
    pub reply_thread_id: Option<String>,
    #[serde(rename = "ReserveTokens")]
    pub reserve_tokens: Option<String>,
    #[serde(rename = "Result")]
    pub result: Option<String>,
    #[serde(rename = "SandboxAllowMcpServers")]
    pub sandbox_allow_mcp_servers: Option<bool>,
    #[serde(rename = "SandboxAllowPackageManagers")]
    pub sandbox_allow_package_managers: Option<bool>,
    #[serde(rename = "SandboxAllowedHostsJson")]
    pub sandbox_allowed_hosts_json: Option<String>,
    #[serde(rename = "SandboxId")]
    pub sandbox_id: Option<String>,
    #[serde(rename = "SandboxNetworkingType")]
    pub sandbox_networking_type: Option<String>,
    #[serde(rename = "SandboxPackagesJson")]
    pub sandbox_packages_json: Option<String>,
    #[serde(rename = "SandboxProvider")]
    pub sandbox_provider: Option<String>,
    #[serde(rename = "SandboxUrl")]
    pub sandbox_url: Option<String>,
    #[serde(rename = "SessionDepth")]
    pub session_depth: Option<i64>,
    #[serde(rename = "SessionEntriesMaterialized")]
    pub session_entries_materialized: Option<String>,
    #[serde(rename = "SessionFileId")]
    pub session_file_id: Option<String>,
    #[serde(rename = "SessionLeafId")]
    pub session_leaf_id: Option<String>,
    #[serde(rename = "SessionMode")]
    pub session_mode: Option<String>,
    #[serde(rename = "SoulId")]
    pub soul_id: Option<String>,
    #[serde(rename = "Status")]
    pub status: Option<String>,
    #[serde(rename = "SteeringMessages")]
    pub steering_messages: Option<String>,
    #[serde(rename = "SystemPrompt")]
    pub system_prompt: Option<String>,
    #[serde(rename = "SystemPromptFileId")]
    pub system_prompt_file_id: Option<String>,
    #[serde(rename = "SystemPromptHash")]
    pub system_prompt_hash: Option<String>,
    #[serde(rename = "TemperApiUrl")]
    pub temper_api_url: Option<String>,
    #[serde(rename = "ToolsEnabled")]
    pub tools_enabled: Option<String>,
    #[serde(rename = "TurnCount")]
    pub turn_count: Option<i64>,
    #[serde(rename = "UserMessage")]
    pub user_message: Option<String>,
    #[serde(rename = "Workdir")]
    pub workdir: Option<String>,
    #[serde(rename = "WorkspaceId")]
    pub workspace_id: Option<String>,
}

#[derive(Debug, Clone, serde::Serialize)]
pub struct SessionCreate {
    #[serde(rename = "ActivePlanId")]
    pub active_plan_id: Option<String>,
    #[serde(rename = "AgentId")]
    pub agent_id: Option<String>,
    #[serde(rename = "ChildSessionIds")]
    pub child_session_ids: Option<String>,
    #[serde(rename = "CompactionAuthRetryCount")]
    pub compaction_auth_retry_count: Option<i64>,
    #[serde(rename = "CompactionCount")]
    pub compaction_count: Option<i64>,
    #[serde(rename = "CompactionModel")]
    pub compaction_model: Option<String>,
    #[serde(rename = "CompactionSkippedLeafId")]
    pub compaction_skipped_leaf_id: Option<String>,
    #[serde(rename = "CompactionSkippedReason")]
    pub compaction_skipped_reason: Option<String>,
    #[serde(rename = "ContextTokens")]
    pub context_tokens: Option<i64>,
    #[serde(rename = "Conversation")]
    pub conversation: Option<String>,
    #[serde(rename = "ConversationFileId")]
    pub conversation_file_id: Option<String>,
    #[serde(rename = "CostCents")]
    pub cost_cents: Option<String>,
    #[serde(rename = "ErrorMessage")]
    pub error_message: Option<String>,
    #[serde(rename = "FileManifestId")]
    pub file_manifest_id: Option<String>,
    #[serde(rename = "FollowUpCount")]
    pub follow_up_count: Option<i64>,
    #[serde(rename = "GenAiParentSpanId")]
    pub gen_ai_parent_span_id: Option<String>,
    #[serde(rename = "GenAiParentTraceId")]
    pub gen_ai_parent_trace_id: Option<String>,
    #[serde(rename = "HasResult")]
    pub has_result: Option<bool>,
    #[serde(rename = "HeartbeatTimeoutSeconds")]
    pub heartbeat_timeout_seconds: Option<String>,
    #[serde(rename = "HookPolicy")]
    pub hook_policy: Option<String>,
    #[serde(rename = "Id")]
    pub id: String,
    #[serde(rename = "InputTokens")]
    pub input_tokens: Option<i64>,
    #[serde(rename = "KeepRecentTokens")]
    pub keep_recent_tokens: Option<String>,
    #[serde(rename = "LastHeartbeatAt")]
    pub last_heartbeat_at: Option<String>,
    #[serde(rename = "LastProgressAt")]
    pub last_progress_at: Option<String>,
    #[serde(rename = "MaxFollowUps")]
    pub max_follow_ups: Option<String>,
    #[serde(rename = "MaxProvisionChecks")]
    pub max_provision_checks: Option<String>,
    #[serde(rename = "MaxTurns")]
    pub max_turns: Option<String>,
    #[serde(rename = "Model")]
    pub model: Option<String>,
    #[serde(rename = "OutputTokens")]
    pub output_tokens: Option<i64>,
    #[serde(rename = "ParentSessionId")]
    pub parent_session_id: Option<String>,
    #[serde(rename = "PendingDecisionId")]
    pub pending_decision_id: Option<String>,
    #[serde(rename = "PendingToolCalls")]
    pub pending_tool_calls: Option<String>,
    #[serde(rename = "PendingToolContext")]
    pub pending_tool_context: Option<String>,
    #[serde(rename = "PrePlanToolsEnabled")]
    pub pre_plan_tools_enabled: Option<String>,
    #[serde(rename = "PreparedContextBytes")]
    pub prepared_context_bytes: Option<i64>,
    #[serde(rename = "PreparedContextContentFilesLoaded")]
    pub prepared_context_content_files_loaded: Option<i64>,
    #[serde(rename = "PreparedContextEntriesLoaded")]
    pub prepared_context_entries_loaded: Option<i64>,
    #[serde(rename = "PreparedContextFileId")]
    pub prepared_context_file_id: Option<String>,
    #[serde(rename = "PreparedContextInlineJson")]
    pub prepared_context_inline_json: Option<String>,
    #[serde(rename = "ProgressToken")]
    pub progress_token: Option<i64>,
    #[serde(rename = "ProjectHarnessId")]
    pub project_harness_id: Option<String>,
    #[serde(rename = "ProjectId")]
    pub project_id: Option<String>,
    #[serde(rename = "Provider")]
    pub provider: Option<String>,
    #[serde(rename = "ProviderAuthCheckedAtMs")]
    pub provider_auth_checked_at_ms: Option<String>,
    #[serde(rename = "ProviderAuthError")]
    pub provider_auth_error: Option<String>,
    #[serde(rename = "ProviderAuthRetryCount")]
    pub provider_auth_retry_count: Option<i64>,
    #[serde(rename = "ProviderAuthStatus")]
    pub provider_auth_status: Option<String>,
    #[serde(rename = "ProviderOptionsJson")]
    pub provider_options_json: Option<String>,
    #[serde(rename = "ProviderRequestBytes")]
    pub provider_request_bytes: Option<i64>,
    #[serde(rename = "ProviderResponseBytes")]
    pub provider_response_bytes: Option<i64>,
    #[serde(rename = "ProviderResponseFileId")]
    pub provider_response_file_id: Option<String>,
    #[serde(rename = "ProviderResponseInlineJson")]
    pub provider_response_inline_json: Option<String>,
    #[serde(rename = "ProvisionCheckCount")]
    pub provision_check_count: Option<i64>,
    #[serde(rename = "ReplFileId")]
    pub repl_file_id: Option<String>,
    #[serde(rename = "ReplyAttachmentsJson")]
    pub reply_attachments_json: Option<String>,
    #[serde(rename = "ReplyChannelEntityId")]
    pub reply_channel_entity_id: Option<String>,
    #[serde(rename = "ReplyChannelId")]
    pub reply_channel_id: Option<String>,
    #[serde(rename = "ReplyChannelType")]
    pub reply_channel_type: Option<String>,
    #[serde(rename = "ReplyRouteSource")]
    pub reply_route_source: Option<String>,
    #[serde(rename = "ReplyThreadId")]
    pub reply_thread_id: Option<String>,
    #[serde(rename = "ReserveTokens")]
    pub reserve_tokens: Option<String>,
    #[serde(rename = "Result")]
    pub result: Option<String>,
    #[serde(rename = "SandboxAllowMcpServers")]
    pub sandbox_allow_mcp_servers: Option<bool>,
    #[serde(rename = "SandboxAllowPackageManagers")]
    pub sandbox_allow_package_managers: Option<bool>,
    #[serde(rename = "SandboxAllowedHostsJson")]
    pub sandbox_allowed_hosts_json: Option<String>,
    #[serde(rename = "SandboxId")]
    pub sandbox_id: Option<String>,
    #[serde(rename = "SandboxNetworkingType")]
    pub sandbox_networking_type: Option<String>,
    #[serde(rename = "SandboxPackagesJson")]
    pub sandbox_packages_json: Option<String>,
    #[serde(rename = "SandboxProvider")]
    pub sandbox_provider: Option<String>,
    #[serde(rename = "SandboxUrl")]
    pub sandbox_url: Option<String>,
    #[serde(rename = "SessionDepth")]
    pub session_depth: Option<i64>,
    #[serde(rename = "SessionEntriesMaterialized")]
    pub session_entries_materialized: Option<String>,
    #[serde(rename = "SessionFileId")]
    pub session_file_id: Option<String>,
    #[serde(rename = "SessionLeafId")]
    pub session_leaf_id: Option<String>,
    #[serde(rename = "SessionMode")]
    pub session_mode: Option<String>,
    #[serde(rename = "SoulId")]
    pub soul_id: Option<String>,
    #[serde(rename = "Status")]
    pub status: Option<String>,
    #[serde(rename = "SteeringMessages")]
    pub steering_messages: Option<String>,
    #[serde(rename = "SystemPrompt")]
    pub system_prompt: Option<String>,
    #[serde(rename = "SystemPromptFileId")]
    pub system_prompt_file_id: Option<String>,
    #[serde(rename = "SystemPromptHash")]
    pub system_prompt_hash: Option<String>,
    #[serde(rename = "TemperApiUrl")]
    pub temper_api_url: Option<String>,
    #[serde(rename = "ToolsEnabled")]
    pub tools_enabled: Option<String>,
    #[serde(rename = "TurnCount")]
    pub turn_count: Option<i64>,
    #[serde(rename = "UserMessage")]
    pub user_message: Option<String>,
    #[serde(rename = "Workdir")]
    pub workdir: Option<String>,
    #[serde(rename = "WorkspaceId")]
    pub workspace_id: Option<String>,
}

#[derive(Debug, Clone, Default, serde::Serialize)]
pub struct SessionPatch {
    #[serde(rename = "ActivePlanId", skip_serializing_if = "Option::is_none")]
    pub active_plan_id: Option<Option<String>>,
    #[serde(rename = "AgentId", skip_serializing_if = "Option::is_none")]
    pub agent_id: Option<Option<String>>,
    #[serde(rename = "ChildSessionIds", skip_serializing_if = "Option::is_none")]
    pub child_session_ids: Option<Option<String>>,
    #[serde(rename = "CompactionAuthRetryCount", skip_serializing_if = "Option::is_none")]
    pub compaction_auth_retry_count: Option<Option<i64>>,
    #[serde(rename = "CompactionCount", skip_serializing_if = "Option::is_none")]
    pub compaction_count: Option<Option<i64>>,
    #[serde(rename = "CompactionModel", skip_serializing_if = "Option::is_none")]
    pub compaction_model: Option<Option<String>>,
    #[serde(rename = "CompactionSkippedLeafId", skip_serializing_if = "Option::is_none")]
    pub compaction_skipped_leaf_id: Option<Option<String>>,
    #[serde(rename = "CompactionSkippedReason", skip_serializing_if = "Option::is_none")]
    pub compaction_skipped_reason: Option<Option<String>>,
    #[serde(rename = "ContextTokens", skip_serializing_if = "Option::is_none")]
    pub context_tokens: Option<Option<i64>>,
    #[serde(rename = "Conversation", skip_serializing_if = "Option::is_none")]
    pub conversation: Option<Option<String>>,
    #[serde(rename = "ConversationFileId", skip_serializing_if = "Option::is_none")]
    pub conversation_file_id: Option<Option<String>>,
    #[serde(rename = "CostCents", skip_serializing_if = "Option::is_none")]
    pub cost_cents: Option<Option<String>>,
    #[serde(rename = "ErrorMessage", skip_serializing_if = "Option::is_none")]
    pub error_message: Option<Option<String>>,
    #[serde(rename = "FileManifestId", skip_serializing_if = "Option::is_none")]
    pub file_manifest_id: Option<Option<String>>,
    #[serde(rename = "FollowUpCount", skip_serializing_if = "Option::is_none")]
    pub follow_up_count: Option<Option<i64>>,
    #[serde(rename = "GenAiParentSpanId", skip_serializing_if = "Option::is_none")]
    pub gen_ai_parent_span_id: Option<Option<String>>,
    #[serde(rename = "GenAiParentTraceId", skip_serializing_if = "Option::is_none")]
    pub gen_ai_parent_trace_id: Option<Option<String>>,
    #[serde(rename = "HasResult", skip_serializing_if = "Option::is_none")]
    pub has_result: Option<Option<bool>>,
    #[serde(rename = "HeartbeatTimeoutSeconds", skip_serializing_if = "Option::is_none")]
    pub heartbeat_timeout_seconds: Option<Option<String>>,
    #[serde(rename = "HookPolicy", skip_serializing_if = "Option::is_none")]
    pub hook_policy: Option<Option<String>>,
    #[serde(rename = "Id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "InputTokens", skip_serializing_if = "Option::is_none")]
    pub input_tokens: Option<Option<i64>>,
    #[serde(rename = "KeepRecentTokens", skip_serializing_if = "Option::is_none")]
    pub keep_recent_tokens: Option<Option<String>>,
    #[serde(rename = "LastHeartbeatAt", skip_serializing_if = "Option::is_none")]
    pub last_heartbeat_at: Option<Option<String>>,
    #[serde(rename = "LastProgressAt", skip_serializing_if = "Option::is_none")]
    pub last_progress_at: Option<Option<String>>,
    #[serde(rename = "MaxFollowUps", skip_serializing_if = "Option::is_none")]
    pub max_follow_ups: Option<Option<String>>,
    #[serde(rename = "MaxProvisionChecks", skip_serializing_if = "Option::is_none")]
    pub max_provision_checks: Option<Option<String>>,
    #[serde(rename = "MaxTurns", skip_serializing_if = "Option::is_none")]
    pub max_turns: Option<Option<String>>,
    #[serde(rename = "Model", skip_serializing_if = "Option::is_none")]
    pub model: Option<Option<String>>,
    #[serde(rename = "OutputTokens", skip_serializing_if = "Option::is_none")]
    pub output_tokens: Option<Option<i64>>,
    #[serde(rename = "ParentSessionId", skip_serializing_if = "Option::is_none")]
    pub parent_session_id: Option<Option<String>>,
    #[serde(rename = "PendingDecisionId", skip_serializing_if = "Option::is_none")]
    pub pending_decision_id: Option<Option<String>>,
    #[serde(rename = "PendingToolCalls", skip_serializing_if = "Option::is_none")]
    pub pending_tool_calls: Option<Option<String>>,
    #[serde(rename = "PendingToolContext", skip_serializing_if = "Option::is_none")]
    pub pending_tool_context: Option<Option<String>>,
    #[serde(rename = "PrePlanToolsEnabled", skip_serializing_if = "Option::is_none")]
    pub pre_plan_tools_enabled: Option<Option<String>>,
    #[serde(rename = "PreparedContextBytes", skip_serializing_if = "Option::is_none")]
    pub prepared_context_bytes: Option<Option<i64>>,
    #[serde(rename = "PreparedContextContentFilesLoaded", skip_serializing_if = "Option::is_none")]
    pub prepared_context_content_files_loaded: Option<Option<i64>>,
    #[serde(rename = "PreparedContextEntriesLoaded", skip_serializing_if = "Option::is_none")]
    pub prepared_context_entries_loaded: Option<Option<i64>>,
    #[serde(rename = "PreparedContextFileId", skip_serializing_if = "Option::is_none")]
    pub prepared_context_file_id: Option<Option<String>>,
    #[serde(rename = "PreparedContextInlineJson", skip_serializing_if = "Option::is_none")]
    pub prepared_context_inline_json: Option<Option<String>>,
    #[serde(rename = "ProgressToken", skip_serializing_if = "Option::is_none")]
    pub progress_token: Option<Option<i64>>,
    #[serde(rename = "ProjectHarnessId", skip_serializing_if = "Option::is_none")]
    pub project_harness_id: Option<Option<String>>,
    #[serde(rename = "ProjectId", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<Option<String>>,
    #[serde(rename = "Provider", skip_serializing_if = "Option::is_none")]
    pub provider: Option<Option<String>>,
    #[serde(rename = "ProviderAuthCheckedAtMs", skip_serializing_if = "Option::is_none")]
    pub provider_auth_checked_at_ms: Option<Option<String>>,
    #[serde(rename = "ProviderAuthError", skip_serializing_if = "Option::is_none")]
    pub provider_auth_error: Option<Option<String>>,
    #[serde(rename = "ProviderAuthRetryCount", skip_serializing_if = "Option::is_none")]
    pub provider_auth_retry_count: Option<Option<i64>>,
    #[serde(rename = "ProviderAuthStatus", skip_serializing_if = "Option::is_none")]
    pub provider_auth_status: Option<Option<String>>,
    #[serde(rename = "ProviderOptionsJson", skip_serializing_if = "Option::is_none")]
    pub provider_options_json: Option<Option<String>>,
    #[serde(rename = "ProviderRequestBytes", skip_serializing_if = "Option::is_none")]
    pub provider_request_bytes: Option<Option<i64>>,
    #[serde(rename = "ProviderResponseBytes", skip_serializing_if = "Option::is_none")]
    pub provider_response_bytes: Option<Option<i64>>,
    #[serde(rename = "ProviderResponseFileId", skip_serializing_if = "Option::is_none")]
    pub provider_response_file_id: Option<Option<String>>,
    #[serde(rename = "ProviderResponseInlineJson", skip_serializing_if = "Option::is_none")]
    pub provider_response_inline_json: Option<Option<String>>,
    #[serde(rename = "ProvisionCheckCount", skip_serializing_if = "Option::is_none")]
    pub provision_check_count: Option<Option<i64>>,
    #[serde(rename = "ReplFileId", skip_serializing_if = "Option::is_none")]
    pub repl_file_id: Option<Option<String>>,
    #[serde(rename = "ReplyAttachmentsJson", skip_serializing_if = "Option::is_none")]
    pub reply_attachments_json: Option<Option<String>>,
    #[serde(rename = "ReplyChannelEntityId", skip_serializing_if = "Option::is_none")]
    pub reply_channel_entity_id: Option<Option<String>>,
    #[serde(rename = "ReplyChannelId", skip_serializing_if = "Option::is_none")]
    pub reply_channel_id: Option<Option<String>>,
    #[serde(rename = "ReplyChannelType", skip_serializing_if = "Option::is_none")]
    pub reply_channel_type: Option<Option<String>>,
    #[serde(rename = "ReplyRouteSource", skip_serializing_if = "Option::is_none")]
    pub reply_route_source: Option<Option<String>>,
    #[serde(rename = "ReplyThreadId", skip_serializing_if = "Option::is_none")]
    pub reply_thread_id: Option<Option<String>>,
    #[serde(rename = "ReserveTokens", skip_serializing_if = "Option::is_none")]
    pub reserve_tokens: Option<Option<String>>,
    #[serde(rename = "Result", skip_serializing_if = "Option::is_none")]
    pub result: Option<Option<String>>,
    #[serde(rename = "SandboxAllowMcpServers", skip_serializing_if = "Option::is_none")]
    pub sandbox_allow_mcp_servers: Option<Option<bool>>,
    #[serde(rename = "SandboxAllowPackageManagers", skip_serializing_if = "Option::is_none")]
    pub sandbox_allow_package_managers: Option<Option<bool>>,
    #[serde(rename = "SandboxAllowedHostsJson", skip_serializing_if = "Option::is_none")]
    pub sandbox_allowed_hosts_json: Option<Option<String>>,
    #[serde(rename = "SandboxId", skip_serializing_if = "Option::is_none")]
    pub sandbox_id: Option<Option<String>>,
    #[serde(rename = "SandboxNetworkingType", skip_serializing_if = "Option::is_none")]
    pub sandbox_networking_type: Option<Option<String>>,
    #[serde(rename = "SandboxPackagesJson", skip_serializing_if = "Option::is_none")]
    pub sandbox_packages_json: Option<Option<String>>,
    #[serde(rename = "SandboxProvider", skip_serializing_if = "Option::is_none")]
    pub sandbox_provider: Option<Option<String>>,
    #[serde(rename = "SandboxUrl", skip_serializing_if = "Option::is_none")]
    pub sandbox_url: Option<Option<String>>,
    #[serde(rename = "SessionDepth", skip_serializing_if = "Option::is_none")]
    pub session_depth: Option<Option<i64>>,
    #[serde(rename = "SessionEntriesMaterialized", skip_serializing_if = "Option::is_none")]
    pub session_entries_materialized: Option<Option<String>>,
    #[serde(rename = "SessionFileId", skip_serializing_if = "Option::is_none")]
    pub session_file_id: Option<Option<String>>,
    #[serde(rename = "SessionLeafId", skip_serializing_if = "Option::is_none")]
    pub session_leaf_id: Option<Option<String>>,
    #[serde(rename = "SessionMode", skip_serializing_if = "Option::is_none")]
    pub session_mode: Option<Option<String>>,
    #[serde(rename = "SoulId", skip_serializing_if = "Option::is_none")]
    pub soul_id: Option<Option<String>>,
    #[serde(rename = "Status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Option<String>>,
    #[serde(rename = "SteeringMessages", skip_serializing_if = "Option::is_none")]
    pub steering_messages: Option<Option<String>>,
    #[serde(rename = "SystemPrompt", skip_serializing_if = "Option::is_none")]
    pub system_prompt: Option<Option<String>>,
    #[serde(rename = "SystemPromptFileId", skip_serializing_if = "Option::is_none")]
    pub system_prompt_file_id: Option<Option<String>>,
    #[serde(rename = "SystemPromptHash", skip_serializing_if = "Option::is_none")]
    pub system_prompt_hash: Option<Option<String>>,
    #[serde(rename = "TemperApiUrl", skip_serializing_if = "Option::is_none")]
    pub temper_api_url: Option<Option<String>>,
    #[serde(rename = "ToolsEnabled", skip_serializing_if = "Option::is_none")]
    pub tools_enabled: Option<Option<String>>,
    #[serde(rename = "TurnCount", skip_serializing_if = "Option::is_none")]
    pub turn_count: Option<Option<i64>>,
    #[serde(rename = "UserMessage", skip_serializing_if = "Option::is_none")]
    pub user_message: Option<Option<String>>,
    #[serde(rename = "Workdir", skip_serializing_if = "Option::is_none")]
    pub workdir: Option<Option<String>>,
    #[serde(rename = "WorkspaceId", skip_serializing_if = "Option::is_none")]
    pub workspace_id: Option<Option<String>>,
}

#[derive(Debug, Clone, serde::Serialize)]
pub struct SessionResumeWithPlanApprovalInput {
    #[serde(rename = "session_mode")]
    pub session_mode: Option<String>,
    #[serde(rename = "tools_enabled")]
    pub tools_enabled: Option<String>,
    #[serde(rename = "pre_plan_tools_enabled")]
    pub pre_plan_tools_enabled: Option<String>,
}

pub struct SessionFilter(FilterV1);
impl SessionFilter {
    pub fn and(operands: Vec<Self>) -> Self { Self(FilterV1::And { operands: operands.into_iter().map(|value| value.0).collect() }) }
    pub fn or(operands: Vec<Self>) -> Self { Self(FilterV1::Or { operands: operands.into_iter().map(|value| value.0).collect() }) }
    pub fn not(operand: Self) -> Self { Self(FilterV1::Not { operand: Box::new(operand.0) }) }
}

pub struct SessionOrder(OrderV1);
impl SessionOrder {
}

pub struct SessionClient { data: DataClient }
impl SessionClient {
    pub const ENTITY_TYPE: &'static str = "TemperPaw.Session";
    pub fn new() -> Self { Self { data: DataClient::default() } }
    pub fn get(&mut self, id: impl Into<String>) -> Result<TypedEntity<Session>, ModuleDataError> { decode_entity(self.data.call(DataOperationV1::EntityGet { entity_type: Self::ENTITY_TYPE.into(), entity_id: id.into(), at_least_sequence: None })?) }
    pub fn resume_with_plan_approval(&mut self, id: impl Into<String>, expected_sequence: Option<u64>, params: SessionResumeWithPlanApprovalInput) -> Result<TypedAction<Session>, ModuleDataError> { decode_action(self.data.call(DataOperationV1::ActionInvoke { entity_type: Self::ENTITY_TYPE.into(), entity_id: id.into(), action: "ResumeWithPlanApproval".into(), expected_sequence, params: serde_json::to_value(params).map_err(invalid_generated_value)?.as_object().cloned().unwrap_or_default() })?) }
}

#[used]
pub static TEMPER_MODULE_GRANT_DIGEST: &str = "15e2dceb6e275b24820f2562e3441a635c08d1819d459b0c600c3d58310bb316";
#[used]
pub static TEMPER_MODULE_CLOSURE_DIGEST: &str = "sha256:53f06b43315017309aa0fcf9479a2117184c64a2d0aa8e7359abb14e07edf65b";
#[used]
pub static TEMPER_MODULE_DEPENDENCY_LOCK_DIGEST: &str = "sha256:53f06b43315017309aa0fcf9479a2117184c64a2d0aa8e7359abb14e07edf65b";
#[used]
pub static TEMPER_MODULE_SCHEMA_DIGEST: &str = "8d4350d520b4551784680b8ed94193ef39ce4539acda7903a1f4479a6d131441";
#[used]
pub static TEMPER_MODULE_USED_SYMBOLS_DIGEST: &str = "0fd0bd4db08f19be5aa689fcee18cf123944c4861b645828dab58e7ab6124fab";
