// @generated by temper-codegen; do not edit.
use temper_wasm_sdk::data::*;

fn invalid_generated_value(error: serde_json::Error) -> ModuleDataError { ModuleDataError::new(ModuleDataErrorKind::InvalidRequest, "GeneratedValueEncodingFailed", error.to_string(), Retryability::Never) }

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct SessionId(pub String);

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Session {
    #[serde(rename = "ActivePlanId")]
    pub active_plan_id: Option<String>,
    #[serde(rename = "AgentId")]
    pub agent_id: Option<String>,
    #[serde(rename = "ChildSessionIds")]
    pub child_session_ids: Option<String>,
    #[serde(rename = "CompactionAuthRetryCount")]
    pub compaction_auth_retry_count: Option<i64>,
    #[serde(rename = "CompactionCount")]
    pub compaction_count: Option<i64>,
    #[serde(rename = "CompactionModel")]
    pub compaction_model: Option<String>,
    #[serde(rename = "CompactionSkippedLeafId")]
    pub compaction_skipped_leaf_id: Option<String>,
    #[serde(rename = "CompactionSkippedReason")]
    pub compaction_skipped_reason: Option<String>,
    #[serde(rename = "ContextTokens")]
    pub context_tokens: Option<i64>,
    #[serde(rename = "Conversation")]
    pub conversation: Option<String>,
    #[serde(rename = "ConversationFileId")]
    pub conversation_file_id: Option<String>,
    #[serde(rename = "CostCents")]
    pub cost_cents: Option<String>,
    #[serde(rename = "ErrorMessage")]
    pub error_message: Option<String>,
    #[serde(rename = "FileManifestId")]
    pub file_manifest_id: Option<String>,
    #[serde(rename = "FollowUpCount")]
    pub follow_up_count: Option<i64>,
    #[serde(rename = "GenAiParentSpanId")]
    pub gen_ai_parent_span_id: Option<String>,
    #[serde(rename = "GenAiParentTraceId")]
    pub gen_ai_parent_trace_id: Option<String>,
    #[serde(rename = "HasResult")]
    pub has_result: Option<bool>,
    #[serde(rename = "HeartbeatTimeoutSeconds")]
    pub heartbeat_timeout_seconds: Option<String>,
    #[serde(rename = "HookPolicy")]
    pub hook_policy: Option<String>,
    #[serde(rename = "Id")]
    pub id: String,
    #[serde(rename = "InputTokens")]
    pub input_tokens: Option<i64>,
    #[serde(rename = "KeepRecentTokens")]
    pub keep_recent_tokens: Option<String>,
    #[serde(rename = "LastHeartbeatAt")]
    pub last_heartbeat_at: Option<String>,
    #[serde(rename = "LastProgressAt")]
    pub last_progress_at: Option<String>,
    #[serde(rename = "MaxFollowUps")]
    pub max_follow_ups: Option<String>,
    #[serde(rename = "MaxProvisionChecks")]
    pub max_provision_checks: Option<String>,
    #[serde(rename = "MaxTurns")]
    pub max_turns: Option<String>,
    #[serde(rename = "Model")]
    pub model: Option<String>,
    #[serde(rename = "OutputTokens")]
    pub output_tokens: Option<i64>,
    #[serde(rename = "ParentSessionId")]
    pub parent_session_id: Option<String>,
    #[serde(rename = "PendingDecisionId")]
    pub pending_decision_id: Option<String>,
    #[serde(rename = "PendingToolCalls")]
    pub pending_tool_calls: Option<String>,
    #[serde(rename = "PendingToolContext")]
    pub pending_tool_context: Option<String>,
    #[serde(rename = "PrePlanToolsEnabled")]
    pub pre_plan_tools_enabled: Option<String>,
    #[serde(rename = "PreparedContextBytes")]
    pub prepared_context_bytes: Option<i64>,
    #[serde(rename = "PreparedContextContentFilesLoaded")]
    pub prepared_context_content_files_loaded: Option<i64>,
    #[serde(rename = "PreparedContextEntriesLoaded")]
    pub prepared_context_entries_loaded: Option<i64>,
    #[serde(rename = "PreparedContextFileId")]
    pub prepared_context_file_id: Option<String>,
    #[serde(rename = "PreparedContextInlineJson")]
    pub prepared_context_inline_json: Option<String>,
    #[serde(rename = "ProgressToken")]
    pub progress_token: Option<i64>,
    #[serde(rename = "ProjectHarnessId")]
    pub project_harness_id: Option<String>,
    #[serde(rename = "ProjectId")]
    pub project_id: Option<String>,
    #[serde(rename = "Provider")]
    pub provider: Option<String>,
    #[serde(rename = "ProviderAuthCheckedAtMs")]
    pub provider_auth_checked_at_ms: Option<String>,
    #[serde(rename = "ProviderAuthError")]
    pub provider_auth_error: Option<String>,
    #[serde(rename = "ProviderAuthRetryCount")]
    pub provider_auth_retry_count: Option<i64>,
    #[serde(rename = "ProviderAuthStatus")]
    pub provider_auth_status: Option<String>,
    #[serde(rename = "ProviderOptionsJson")]
    pub provider_options_json: Option<String>,
    #[serde(rename = "ProviderRequestBytes")]
    pub provider_request_bytes: Option<i64>,
    #[serde(rename = "ProviderResponseBytes")]
    pub provider_response_bytes: Option<i64>,
    #[serde(rename = "ProviderResponseFileId")]
    pub provider_response_file_id: Option<String>,
    #[serde(rename = "ProviderResponseInlineJson")]
    pub provider_response_inline_json: Option<String>,
    #[serde(rename = "ProvisionCheckCount")]
    pub provision_check_count: Option<i64>,
    #[serde(rename = "ReplFileId")]
    pub repl_file_id: Option<String>,
    #[serde(rename = "ReplyAttachmentsJson")]
    pub reply_attachments_json: Option<String>,
    #[serde(rename = "ReplyChannelEntityId")]
    pub reply_channel_entity_id: Option<String>,
    #[serde(rename = "ReplyChannelId")]
    pub reply_channel_id: Option<String>,
    #[serde(rename = "ReplyChannelType")]
    pub reply_channel_type: Option<String>,
    #[serde(rename = "ReplyRouteSource")]
    pub reply_route_source: Option<String>,
    #[serde(rename = "ReplyThreadId")]
    pub reply_thread_id: Option<String>,
    #[serde(rename = "ReserveTokens")]
    pub reserve_tokens: Option<String>,
    #[serde(rename = "Result")]
    pub result: Option<String>,
    #[serde(rename = "SandboxAllowMcpServers")]
    pub sandbox_allow_mcp_servers: Option<bool>,
    #[serde(rename = "SandboxAllowPackageManagers")]
    pub sandbox_allow_package_managers: Option<bool>,
    #[serde(rename = "SandboxAllowedHostsJson")]
    pub sandbox_allowed_hosts_json: Option<String>,
    #[serde(rename = "SandboxId")]
    pub sandbox_id: Option<String>,
    #[serde(rename = "SandboxNetworkingType")]
    pub sandbox_networking_type: Option<String>,
    #[serde(rename = "SandboxPackagesJson")]
    pub sandbox_packages_json: Option<String>,
    #[serde(rename = "SandboxProvider")]
    pub sandbox_provider: Option<String>,
    #[serde(rename = "SandboxUrl")]
    pub sandbox_url: Option<String>,
    #[serde(rename = "SessionDepth")]
    pub session_depth: Option<i64>,
    #[serde(rename = "SessionEntriesMaterialized")]
    pub session_entries_materialized: Option<String>,
    #[serde(rename = "SessionFileId")]
    pub session_file_id: Option<String>,
    #[serde(rename = "SessionLeafId")]
    pub session_leaf_id: Option<String>,
    #[serde(rename = "SessionMode")]
    pub session_mode: Option<String>,
    #[serde(rename = "SoulId")]
    pub soul_id: Option<String>,
    #[serde(rename = "Status")]
    pub status: Option<String>,
    #[serde(rename = "SteeringMessages")]
    pub steering_messages: Option<String>,
    #[serde(rename = "SystemPrompt")]
    pub system_prompt: Option<String>,
    #[serde(rename = "SystemPromptFileId")]
    pub system_prompt_file_id: Option<String>,
    #[serde(rename = "SystemPromptHash")]
    pub system_prompt_hash: Option<String>,
    #[serde(rename = "TemperApiUrl")]
    pub temper_api_url: Option<String>,
    #[serde(rename = "ToolsEnabled")]
    pub tools_enabled: Option<String>,
    #[serde(rename = "TurnCount")]
    pub turn_count: Option<i64>,
    #[serde(rename = "UserMessage")]
    pub user_message: Option<String>,
    #[serde(rename = "Workdir")]
    pub workdir: Option<String>,
    #[serde(rename = "WorkspaceId")]
    pub workspace_id: Option<String>,
}

#[derive(Debug, Clone, serde::Serialize)]
pub struct SessionResumeWithPlanApprovalInput {
    #[serde(rename = "session_mode")]
    pub session_mode: Option<String>,
    #[serde(rename = "tools_enabled")]
    pub tools_enabled: Option<String>,
    #[serde(rename = "pre_plan_tools_enabled")]
    pub pre_plan_tools_enabled: Option<String>,
}

pub struct SessionClient { data: DataClient }
impl SessionClient {
    pub const ENTITY_TYPE: &'static str = "TemperPaw.Session";
    pub fn new() -> Self { Self { data: DataClient::default() } }
    pub fn get(&mut self, id: impl Into<String>) -> Result<TypedEntity<Session>, ModuleDataError> { decode_entity(self.data.call(DataOperationV1::EntityGet { entity_type: Self::ENTITY_TYPE.into(), entity_id: id.into(), at_least_sequence: None })?) }
    pub fn resume_with_plan_approval(&mut self, id: impl Into<String>, expected_sequence: Option<u64>, params: SessionResumeWithPlanApprovalInput) -> Result<TypedAction<Session>, ModuleDataError> { decode_action(self.data.call(DataOperationV1::ActionInvoke { entity_type: Self::ENTITY_TYPE.into(), entity_id: id.into(), action: "ResumeWithPlanApproval".into(), expected_sequence, params: serde_json::to_value(params).map_err(invalid_generated_value)?.as_object().cloned().unwrap_or_default() })?) }
}

#[used]
pub static TEMPER_MODULE_GRANT_DIGEST: &str = "15e2dceb6e275b24820f2562e3441a635c08d1819d459b0c600c3d58310bb316";
#[used]
pub static TEMPER_MODULE_CLOSURE_DIGEST: &str = "sha256:d4c157a836cc82a4f27f9f8236e142ec9e882a1743ee254f3b57ee55503eb9c9";
#[used]
pub static TEMPER_MODULE_DEPENDENCY_LOCK_DIGEST: &str = "sha256:d4c157a836cc82a4f27f9f8236e142ec9e882a1743ee254f3b57ee55503eb9c9";
#[used]
pub static TEMPER_MODULE_SCHEMA_DIGEST: &str = "bb388d1e9e9d8f45e25cc8ef9c98247a435544b96cae464176df477bf76eb740";
#[used]
pub static TEMPER_MODULE_USED_SYMBOLS_DIGEST: &str = "0fd0bd4db08f19be5aa689fcee18cf123944c4861b645828dab58e7ab6124fab";
