[package]
name = "route-message"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[workspace]

[dependencies]
session-tree-lib = { path = "../../../paw-agent/wasm/session-tree-lib" }
wasm-helpers = { path = "../../../paw-agent/wasm/wasm-helpers" }
temper-wasm-sdk = { git = "https://github.com/nikstern/temper.git", rev = "e8ff002bde3e9512385c2856d733210600e7c253" }
