[package]
name = "register-forecasts"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[workspace]

[dependencies]
temper-wasm-sdk = { git = "https://github.com/nikstern/temper.git", rev = "fa1c4a594f4398c1570a3b3469cadd06efcb5043" }
serde_json = "1"
corridor-embed = { path = "../corridor_embed" }
