[package]
name = "register-forecasts"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[workspace]

[dependencies]
temper-wasm-sdk = { git = "https://github.com/nikstern/temper.git", rev = "f0c431ed0b2a19e3f7834a95cba884ad15085651" }
serde_json = "1"
corridor-embed = { path = "../corridor_embed" }
